[package]
name = "MinecraftWorldPregenerator"
version = "0.1.0"
authors = ["codedcosmos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
clap = "2.33.3"